version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - test-db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  test-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: integration-tests-db
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  db-data:
  pg-data:
